### ISSUE TITLE
Landing page flow chart

### ISSUE THREAD

**Issue by snacks** [Greenstand/Design#7]
Needs to take up less space and be a little clearer with it's text.

Also maybe this process can be explained without the use of the chart, it's a little 2005.

**Comment by snacks** [comment]
I actually like the old chart more, minus the graphics. But yeah it's possible this doesn't need this sort of layout at all. The more interesting thing to chart out might be the simple way the app works with planters. What I mean is "tree planter" is a very dry way to talk about the folks on the ground actually doing the work.

**Comment by snacks** [comment]
related to this topic: where is it explained how the planters are funded?

**Comment by Davidezrajay** [comment]
We have moved this to the backside
